apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/openmind-systems-lab/argocd-go-gitops.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: go-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
